const fs=require('fs');
const path=require('path');
global.window=global;
global.document={querySelector(){return null;},querySelectorAll(){return[];},addEventListener(){},createElement(){return {style:{},classList:{add(){},remove(){},toggle(){}},dataset:{},setAttribute(){},appendChild(){},querySelector(){return null;},querySelectorAll(){return[];},innerHTML:''};},body:{appendChild(){}}};
global.navigator={userAgent:'Node QA Phase35D'};
global.localStorage={_:{},getItem(k){return this._[k]||null},setItem(k,v){this._[k]=String(v)},removeItem(k){delete this._[k]}};
global.AppModuleHost={register(){},listModules(){return [{id:'language-course-entry'}]}};
global.EGTUILayer={openDeepSheet(){return true}};
global.speechSynthesis={speak(){},cancel(){},getVoices(){return[]}};
const vm=require('vm');
const code=fs.readFileSync(path.join(__dirname,'js/modules/language-course-entry-module.js'),'utf8');
vm.runInThisContext(code,{filename:'language-course-entry-module.js'});
const api=global.LanguageAcademyCourseEntry;
const qa=api.phase35dQaSnapshot();
const c2=api.c2ContentSnapshot();
const c1=api.c1ContentSnapshot();
const b2=api.b2ContentSnapshot();
const b1=api.b1ContentSnapshot();
const a2=api.a2ContentSnapshot();
const diag=api.diagnostics();
const errors=[];
if(!qa.ok) errors.push('Phase35D QA not ok');
if(qa.phase!=='35D') errors.push('phase not 35D');
if(!c2.ok || c2.totalTasks!==430 || c2.normalTasks!==350 || c2.speakingTasks!==80) errors.push('C2 totals invalid');
if(c2.expandedLessons!==10 || c2.starterLessons!==0) errors.push('C2 expansion invalid');
if(qa.summary.duplicateTaskIds!==0) errors.push('duplicate task ids found');
if(qa.summary.missingRequired!==0) errors.push('missing required fields found');
if(!qa.uiChecks.allLessonsAvailable || !qa.uiChecks.allLessonsVisible) errors.push('C2 UI level availability invalid');
if(!c1.ok || c1.totalTasks!==430 || c1.speakingTasks!==80) errors.push('C1 regression invalid');
if(!b2.ok || b2.totalTasks!==430 || b2.speakingTasks!==80) errors.push('B2 regression invalid');
if(!b1.ok || b1.totalTasks!==430 || b1.speakingTasks!==80) errors.push('B1 regression invalid');
if(!a2.ok || a2.totalTasks!==430 || a2.speakingTasks!==80) errors.push('A2 regression invalid');
if(!diag.phase35dQa || !diag.phase35dQa.ok) errors.push('diagnostics missing phase35dQa');
if(diag.phase!=='35D') errors.push('diagnostics phase not 35D');
const result={pass:errors.length===0,errors,qaSummary:qa.summary,c2:{ok:c2.ok,phase:c2.phase,lessons:c2.lessons,expandedLessons:c2.expandedLessons,starterLessons:c2.starterLessons,totalTasks:c2.totalTasks,normalTasks:c2.normalTasks,speakingTasks:c2.speakingTasks},c1:{ok:c1.ok,totalTasks:c1.totalTasks,speakingTasks:c1.speakingTasks},b2:{ok:b2.ok,totalTasks:b2.totalTasks,speakingTasks:b2.speakingTasks},b1:{ok:b1.ok,totalTasks:b1.totalTasks,speakingTasks:b1.speakingTasks},a2:{ok:a2.ok,totalTasks:a2.totalTasks,speakingTasks:a2.speakingTasks},diagnostics:{phase:diag.phase,version:diag.version,hasPhase35D:!!diag.phase35dQa}};
fs.writeFileSync(path.join(__dirname,'phase35d_node_snapshot_result.json'), JSON.stringify(result,null,2));
if(errors.length){ console.error(JSON.stringify(result,null,2)); process.exit(1); }
console.log('PASS phase35D snapshot', JSON.stringify(result.qaSummary,null,2));
