const fs=require('fs');
const path=require('path');
global.window=global;
global.document={querySelector(){return null;},querySelectorAll(){return[];},addEventListener(){},createElement(){return {style:{},classList:{add(){},remove(){},toggle(){}},dataset:{},setAttribute(){},appendChild(){},querySelector(){return null;},querySelectorAll(){return[];},innerHTML:''};},body:{appendChild(){}}};
global.navigator={userAgent:'Node QA Phase35A'};
global.localStorage={_:{},getItem(k){return this._[k]||null},setItem(k,v){this._[k]=String(v)},removeItem(k){delete this._[k]}};
global.AppModuleHost={register(){},listModules(){return [{id:'language-course-entry'}]}};
global.EGTUILayer={openDeepSheet(){return true}};
global.speechSynthesis={speak(){},cancel(){},getVoices(){return[]}};
const vm=require('vm');
const code=fs.readFileSync(path.join(__dirname,'js/modules/language-course-entry-module.js'),'utf8');
vm.runInThisContext(code,{filename:'language-course-entry-module.js'});
const api=global.LanguageAcademyCourseEntry;
const c2=api.c2StructureSnapshot();
const c1=api.c1ContentSnapshot();
const b2=api.b2ContentSnapshot();
const b1=api.b1ContentSnapshot();
const a2=api.a2ContentSnapshot();
const diag=api.diagnostics();
const errors=[];
if(!c2.ok) errors.push('C2 snapshot not ok');
if(c2.phase!=='35A') errors.push('phase not 35A');
if(c2.lessons!==10 || c2.totalTasks!==120 || c2.normalTasks!==80 || c2.speakingTasks!==40) errors.push('C2 totals invalid');
if(!c2.lessonFlow.every(x=>x.ok)) errors.push('C2 lesson flow invalid');
if(!c1.ok || c1.totalTasks!==430 || c1.speakingTasks!==80) errors.push('C1 regression invalid');
if(!b2.ok || b2.totalTasks!==430 || b2.speakingTasks!==80) errors.push('B2 regression invalid');
if(!b1.ok || b1.totalTasks!==430 || b1.speakingTasks!==80) errors.push('B1 regression invalid');
if(!a2.ok || a2.totalTasks!==430 || a2.speakingTasks!==80) errors.push('A2 regression invalid');
if(!diag.c2Structure || !diag.c2Structure.ok) errors.push('diagnostics missing c2Structure');
if(diag.phase!=='35A') errors.push('diagnostics phase not 35A');
const result={pass:errors.length===0,errors,c2:{ok:c2.ok,phase:c2.phase,lessons:c2.lessons,totalTasks:c2.totalTasks,normalTasks:c2.normalTasks,speakingTasks:c2.speakingTasks},regression:{a2:{ok:a2.ok,totalTasks:a2.totalTasks,speakingTasks:a2.speakingTasks},b1:{ok:b1.ok,totalTasks:b1.totalTasks,speakingTasks:b1.speakingTasks},b2:{ok:b2.ok,totalTasks:b2.totalTasks,speakingTasks:b2.speakingTasks},c1:{ok:c1.ok,totalTasks:c1.totalTasks,speakingTasks:c1.speakingTasks}},diagnostics:{phase:diag.phase,version:diag.version,hasC2:!!diag.c2Structure}};
fs.writeFileSync(path.join(__dirname,'phase35a_node_snapshot_result.json'), JSON.stringify(result,null,2));
if(errors.length){ console.error(JSON.stringify(result,null,2)); process.exit(1); }
console.log('PASS phase35A snapshot', JSON.stringify(result.c2,null,2));
