const fs=require('fs');
const path=require('path');
global.window=global;
global.document={querySelector(){return null;},querySelectorAll(){return[];},addEventListener(){},createElement(){return {style:{},classList:{add(){},remove(){},toggle(){}},dataset:{},setAttribute(){},appendChild(){},querySelector(){return null;},querySelectorAll(){return[];},innerHTML:''};},body:{appendChild(){}}};
global.navigator={userAgent:'Node QA Phase32D'};
global.localStorage={_:{},getItem(k){return this._[k]||null},setItem(k,v){this._[k]=String(v)},removeItem(k){delete this._[k]}};
global.AppModuleHost={register(){},listModules(){return [{id:'language-course-entry'}]}};
global.EGTUILayer={openDeepSheet(){return true}};
global.speechSynthesis={speak(){},cancel(){},getVoices(){return[]}};
const vm=require('vm');
const code=fs.readFileSync(path.join(__dirname,'js/modules/language-course-entry-module.js'),'utf8');
vm.runInThisContext(code,{filename:'language-course-entry-module.js'});
const api=global.LanguageAcademyCourseEntry;
const qa=api.phase32dQaSnapshot();
const b1=api.b1ContentSnapshot();
const a2=api.a2ContentSnapshot();
const diag=api.diagnostics();
const errors=[];
if(!qa.ok) errors.push('phase32d QA not ok');
if(qa.phase!=='32D') errors.push('phase not 32D');
if(!b1.ok || b1.totalTasks!==430 || b1.normalTasks!==350 || b1.speakingTasks!==80 || b1.expandedLessons!==10 || b1.starterLessons!==0) errors.push('B1 totals invalid');
if(!a2.ok || a2.totalTasks!==430 || a2.speakingTasks!==80) errors.push('A2 regression invalid');
if(qa.duplicateIds.length!==0) errors.push('duplicate ids: '+qa.duplicateIds.join(','));
if(qa.missingFields.length!==0) errors.push('missing fields: '+JSON.stringify(qa.missingFields.slice(0,5)));
if(!qa.speakingFallbackReady) errors.push('speaking fallback not ready');
if(!qa.flowReady) errors.push('flow not ready');
if(!qa.coachReady) errors.push('coach not ready');
if(!qa.cloudSafe) errors.push('cloud not safe');
Object.entries(qa.perLesson).forEach(([id,row])=>{ if(!row.ok) errors.push(id+': '+JSON.stringify(row)); });
if(!diag.phase32dQa || !diag.phase32dQa.ok) errors.push('diagnostics missing phase32dQa');
const result={pass:errors.length===0,errors,qa,b1:{ok:b1.ok,totalTasks:b1.totalTasks,normalTasks:b1.normalTasks,speakingTasks:b1.speakingTasks,expandedLessons:b1.expandedLessons,starterLessons:b1.starterLessons},a2:{ok:a2.ok,totalTasks:a2.totalTasks,speakingTasks:a2.speakingTasks},diagnostics:{phase:diag.phase,version:diag.version,hasPhase32dQa:!!diag.phase32dQa}};
fs.writeFileSync(path.join(__dirname,'phase32d_node_snapshot_result.json'), JSON.stringify(result,null,2));
if(errors.length){ console.error(JSON.stringify(result,null,2)); process.exit(1); }
console.log('PASS phase32D snapshot', JSON.stringify({total:b1.totalTasks,speaking:b1.speakingTasks,unique:qa.uniqueTaskIds},null,2));
