const fs=require('fs');
const path=require('path');
global.window=global;
global.document={querySelector(){return null;},querySelectorAll(){return[];},addEventListener(){},createElement(){return {style:{},classList:{add(){},remove(){},toggle(){}},dataset:{},setAttribute(){},appendChild(){},querySelector(){return null;},querySelectorAll(){return[];},innerHTML:''};},body:{appendChild(){}}};
global.navigator={userAgent:'Node QA Phase33D'};
global.localStorage={_:{},getItem(k){return this._[k]||null},setItem(k,v){this._[k]=String(v)},removeItem(k){delete this._[k]}};
global.AppModuleHost={register(){},listModules(){return [{id:'language-course-entry'}]}};
global.EGTUILayer={openDeepSheet(){return true}};
global.speechSynthesis={speak(){},cancel(){},getVoices(){return[]}};
const vm=require('vm');
const code=fs.readFileSync(path.join(__dirname,'js/modules/language-course-entry-module.js'),'utf8');
vm.runInThisContext(code,{filename:'language-course-entry-module.js'});
const api=global.LanguageAcademyCourseEntry;
const qa=api.phase33dQaSnapshot();
const b2=api.b2ContentSnapshot();
const b1=api.b1ContentSnapshot();
const a2=api.a2ContentSnapshot();
const diag=api.diagnostics();
const errors=[];
if(!qa.ok) errors.push('Phase33D QA not ok');
if(qa.phase!=='33D') errors.push('phase not 33D');
if(!b2.ok || b2.totalTasks!==430 || b2.normalTasks!==350 || b2.speakingTasks!==80) errors.push('B2 totals invalid');
if(b2.expandedLessons!==10 || b2.starterLessons!==0) errors.push('B2 expansion invalid');
if(qa.summary.duplicateTaskIds!==0) errors.push('duplicate task ids found');
if(qa.summary.missingRequired!==0) errors.push('missing required fields found');
if(!qa.uiChecks.allLessonsAvailable || !qa.uiChecks.allLessonsVisible) errors.push('B2 UI level availability invalid');
if(!b1.ok || b1.totalTasks!==430 || b1.speakingTasks!==80) errors.push('B1 regression invalid');
if(!a2.ok || a2.totalTasks!==430 || a2.speakingTasks!==80) errors.push('A2 regression invalid');
if(!diag.phase33dQa || !diag.phase33dQa.ok) errors.push('diagnostics missing phase33dQa');
if(diag.phase!=='33D') errors.push('diagnostics phase not 33D');
const result={pass:errors.length===0,errors,qaSummary:qa.summary,b2:{ok:b2.ok,phase:b2.phase,lessons:b2.lessons,expandedLessons:b2.expandedLessons,starterLessons:b2.starterLessons,totalTasks:b2.totalTasks,normalTasks:b2.normalTasks,speakingTasks:b2.speakingTasks},b1:{ok:b1.ok,totalTasks:b1.totalTasks,speakingTasks:b1.speakingTasks},a2:{ok:a2.ok,totalTasks:a2.totalTasks,speakingTasks:a2.speakingTasks},diagnostics:{phase:diag.phase,version:diag.version,hasPhase33D:!!diag.phase33dQa}};
fs.writeFileSync(path.join(__dirname,'phase33d_node_snapshot_result.json'), JSON.stringify(result,null,2));
if(errors.length){ console.error(JSON.stringify(result,null,2)); process.exit(1); }
console.log('PASS phase33D snapshot', JSON.stringify(result.qaSummary,null,2));
