const fs=require('fs');
const path=require('path');
global.window=global;
global.document={querySelector(){return null;},querySelectorAll(){return[];},addEventListener(){},createElement(){return {style:{},classList:{add(){},remove(){},toggle(){}},dataset:{},setAttribute(){},appendChild(){},querySelector(){return null;},querySelectorAll(){return[];},innerHTML:''};},body:{appendChild(){}}};
global.navigator={userAgent:'Node QA'};
global.localStorage={_:{},getItem(k){return this._[k]||null},setItem(k,v){this._[k]=String(v)},removeItem(k){delete this._[k]}};
global.AppModuleHost={register(){},listModules(){return [{id:'language-course-entry'}]}};
global.EGTUILayer={openDeepSheet(){return true}};
global.speechSynthesis={speak(){},cancel(){},getVoices(){return[]}};
const code=fs.readFileSync(path.join(__dirname,'js/modules/language-course-entry-module.js'),'utf8');
vm=require('vm');
vm.runInThisContext(code,{filename:'language-course-entry-module.js'});
const api=global.LanguageAcademyCourseEntry;
const b1=api.b1ContentSnapshot();
const a2=api.a2ContentSnapshot();
const errors=[];
if(!b1.ok) errors.push('b1 snapshot not ok');
if(b1.phase!=='32C') errors.push('phase not 32C');
if(b1.expandedLessons!==10) errors.push('expandedLessons '+b1.expandedLessons);
if(b1.starterLessons!==0) errors.push('starterLessons '+b1.starterLessons);
if(b1.totalTasks!==430) errors.push('totalTasks '+b1.totalTasks);
if(b1.normalTasks!==350) errors.push('normalTasks '+b1.normalTasks);
if(b1.speakingTasks!==80) errors.push('speakingTasks '+b1.speakingTasks);
Object.entries(b1.perLesson).forEach(([id,row])=>{ if(row.tasks!==43||row.speakingTasks!==8||!row.expandedContent||!row.ok) errors.push(id+JSON.stringify(row)); });
if(!a2.ok || a2.totalTasks!==430 || a2.speakingTasks!==80) errors.push('A2 regression');
const result={pass:errors.length===0,errors,b1,a2:{ok:a2.ok,totalTasks:a2.totalTasks,speakingTasks:a2.speakingTasks}};
fs.writeFileSync(path.join(__dirname,'phase32c_node_snapshot_result.json'), JSON.stringify(result,null,2));
if(errors.length){ console.error(result); process.exit(1); }
console.log('PASS phase32C snapshot', JSON.stringify({total:b1.totalTasks,speaking:b1.speakingTasks,expanded:b1.expandedLessons},null,2));
