const fs=require('fs');
const path=require('path');
global.window=global;
global.document={querySelector(){return null;},querySelectorAll(){return[];},addEventListener(){},createElement(){return {style:{},classList:{add(){},remove(){},toggle(){}},dataset:{},setAttribute(){},appendChild(){},querySelector(){return null;},querySelectorAll(){return[];},innerHTML:''};},body:{appendChild(){}}};
global.navigator={userAgent:'Node QA Phase34A'};
global.localStorage={_:{},getItem(k){return this._[k]||null},setItem(k,v){this._[k]=String(v)},removeItem(k){delete this._[k]}};
global.AppModuleHost={register(){},listModules(){return [{id:'language-course-entry'}]}};
global.EGTUILayer={openDeepSheet(){return true}};
global.speechSynthesis={speak(){},cancel(){},getVoices(){return[]}};
const vm=require('vm');
const code=fs.readFileSync(path.join(__dirname,'js/modules/language-course-entry-module.js'),'utf8');
vm.runInThisContext(code,{filename:'language-course-entry-module.js'});
const api=global.LanguageAcademyCourseEntry;
const c1=api.c1StructureSnapshot();
const b2=api.b2ContentSnapshot();
const b1=api.b1ContentSnapshot();
const a2=api.a2ContentSnapshot();
const diag=api.diagnostics();
const errors=[];
if(!c1.ok) errors.push('C1 structure not ok');
if(c1.phase!=='34A') errors.push('phase not 34A');
if(c1.lessons!==10) errors.push('C1 lessons invalid');
if(c1.totalTasks!==120 || c1.normalTasks!==80 || c1.speakingTasks!==40) errors.push('C1 totals invalid');
Object.entries(c1.perLesson||{}).forEach(([id,row])=>{ if(!row.ok || row.tasks!==12 || row.speakingTasks!==4 || !row.parallelSpeaking) errors.push(id+': '+JSON.stringify(row)); });
if(!b2.ok || b2.totalTasks!==430 || b2.speakingTasks!==80) errors.push('B2 regression invalid');
if(!b1.ok || b1.totalTasks!==430 || b1.speakingTasks!==80) errors.push('B1 regression invalid');
if(!a2.ok || a2.totalTasks!==430 || a2.speakingTasks!==80) errors.push('A2 regression invalid');
if(!diag.c1Structure || !diag.c1Structure.ok) errors.push('diagnostics missing c1Structure');
if(diag.phase!=='34A') errors.push('diagnostics phase not 34A');
const result={pass:errors.length===0,errors,c1:{ok:c1.ok,phase:c1.phase,lessons:c1.lessons,totalTasks:c1.totalTasks,normalTasks:c1.normalTasks,speakingTasks:c1.speakingTasks},b2:{ok:b2.ok,totalTasks:b2.totalTasks,speakingTasks:b2.speakingTasks},b1:{ok:b1.ok,totalTasks:b1.totalTasks,speakingTasks:b1.speakingTasks},a2:{ok:a2.ok,totalTasks:a2.totalTasks,speakingTasks:a2.speakingTasks},diagnostics:{phase:diag.phase,version:diag.version,hasC1Structure:!!diag.c1Structure}};
fs.writeFileSync(path.join(__dirname,'phase34a_node_snapshot_result.json'), JSON.stringify(result,null,2));
if(errors.length){ console.error(JSON.stringify(result,null,2)); process.exit(1); }
console.log('PASS phase34A snapshot', JSON.stringify(result.c1,null,2));
