import json, pathlib, re
root=pathlib.Path('.')
checks=[]
def add(id, ok, details=''):
    checks.append({'id':id,'status':'PASS' if ok else 'FAIL','details':details})
idx=(root/'index.html').read_text()
sw=(root/'service-worker.js').read_text()
cfg=(root/'js/core/app-config.js').read_text()
uc=(root/'update-check.json').read_text()
vd=(root/'js/qa/egt-visual-regression-diff.js').read_text()
cap=(root/'js/qa/egt-visual-state-capture.js').read_text()
add('diff_file_exists', (root/'js/qa/egt-visual-regression-diff.js').exists())
add('index_script_registered', './js/qa/egt-visual-regression-diff.js' in idx)
add('service_worker_asset_registered', './js/qa/egt-visual-regression-diff.js' in sw)
add('service_worker_cache_bumped', "egt-trainer-g54-43-8" in sw)
add('app_config_version', "var VERSION = 'G54.43.8'" in cfg)
add('app_config_label', 'Visual Regression / Capture-Diff' in cfg)
add('update_check_version', 'G54.43.8-2026-06-21' in uc)
add('global_api', 'window.EGTVisualRegressionDiff' in vd)
add('start_modes', '?qa=diff' in vd and 'visual-diff' in vd and '#qa-diff' in vd)
add('compare_api', 'compareCaptures' in vd and 'compareNow' in vd)
add('baseline_import', 'Baseline importieren' in vd and 'localStorage' in vd)
add('layout_shift_detection', 'layout-shifts' in vd and 'rectTolerance' in vd)
add('overflow_detection', 'overflow-regression' in vd and 'pageHorizontalOverflow' in vd)
add('touch_detection', 'touch-target-regression' in vd and 'ok44' in vd)
add('media_detection', 'media-missing' in vd and 'SVG/Canvas' in vd)
add('capture_module_kept', 'window.EGTVisualStateCapture' in cap)
add('test_file_exists', (root/'tests_phase43q_visual_regression_diff.html').exists())
failed=[c for c in checks if c['status']=='FAIL']
out={'phase':'G54.43.8','total':len(checks),'passed':len(checks)-len(failed),'failed':len(failed),'checks':checks}
(root/'phase43q_static_check_result.json').write_text(json.dumps(out,ensure_ascii=False,indent=2))
print(json.dumps(out,ensure_ascii=False,indent=2))
raise SystemExit(1 if failed else 0)
