/* Eignungstest-Trainer · Service Worker · G54.43.8C (2026-06-21)
   Ursache des "alten Layouts trotz Deploy"-Problems: Der fetch-Handler war cache-first,
   d.h. einmal gecachtes app.css/JS wurde nie aktualisiert. Layout-/Logik-Dateien laufen
   jetzt network-first (Cache nur als Offline-Fallback). Neuer CACHE_NAME -> alter Cache
   inkl. veraltetem app.css wird beim activate gelöscht. */
var CACHE_NAME = 'egt-trainer-g54-43-8c';
var ASSETS = [
  './tests_phase43k_analysis_forecast_engine.html',
  './SCHICHTUEBERGABE_PHASE43K_ANALYSE_FORECAST_ENGINE.md',
  './phase43k_analysis_forecast_engine_static_qa_result.json',
  './',
  './404.html',
  './START_HERE.md',
  './docs_PHASE39F_VISUAL_OBSERVER_QA_COCKPIT.md',
  './tests_phase39f_visual_observer.html',
  './js/qa-visual-observer.js',
  './js/qa/egt-live-visual-qa.js',
  './js/qa/egt-visual-state-capture.js',
  './js/qa/egt-visual-regression-diff.js',
  './phase43q_static_check_result.json',
  './tests_phase43q_visual_regression_diff.html',
  './SCHICHTUEBERGABE_PHASE43Q_VISUAL_REGRESSION_CAPTURE_DIFF.md',
  './phase39f_static_qa.py',
  './phase39f_static_qa_result.json',
  './phase39g_visual_observer_report.py',
  './phase39g_visual_observer_result.json',
  './phase39g_static_qa.py',
  './phase39g_static_qa_result.json',
  './docs/PHASE39G_VISUAL_OBSERVER_REPORT.md',
  './css/phase39h-medium-fixes.css',
  './tests_phase39h_medium_fixes.html',
  './phase39h_static_qa.py',
  './phase39h_static_qa_result.json',
  './docs/PHASE39H_MEDIUM_FIXES_REPORT.md',
  './css/phase39i-pixel-polish.css',
  './css/phase43s-iphone-scroll-qa-bubble.css',
  './js/modules/iphone-scroll-qa-hotfix.js',
  './tests_phase43s_iphone_scroll_qa_bubble.html',
  './SCHICHTUEBERGABE_PHASE43S_IPHONE_SCROLL_QA_BUBBLE.md',
  './phase43s_static_scroll_qa_result.json',
  './tests_phase43t_qa_bubble_interaction_fix.html',
  './SCHICHTUEBERGABE_PHASE43T_QA_BUBBLE_INTERACTION_FIX.md',
  './phase43t_static_qa_bubble_interaction_result.json',
  './tests_phase39i_pixel_polish.html',
  './phase39i_static_qa.py',
  './phase39i_static_qa_result.json',
  './docs/PHASE39I_PIXEL_POLISH_REPORT.md',
  './tests_phase42_live_device_qa.html',
  './tests_phase43c_iphone_portrait_visual_scroll.html',
  './SCHICHTUEBERGABE_PHASE43C_IPHONE_PORTRAIT_VISUAL_SCROLL_HOTFIX.md',
  './phase43c_static_qa_result.json',
  './tests_phase43d_analysis_dock_deepsheet.html',
  './SCHICHTUEBERGABE_PHASE43D_ANALYSE_DOCK_DEEPSHEET_HOTFIX.md',
  './phase43d_static_qa_result.json',
  './phase42_live_device_qa.py',
  './phase42_live_device_qa_result.json',
  './docs/PHASE42_LIVE_DEVICE_QA.md',
  './tests_phase41_github_pages_deploy_check.html',
  './phase41_deploy_readiness_qa.py',
  './phase41_deploy_readiness_qa_result.json',
  './docs/PHASE41_GITHUB_PAGES_DEPLOY_CHECK.md',
  './tests_phase40_golden_master_qa.html',
  './phase40_golden_master_qa.py',
  './phase40_golden_master_qa_result.json',
  './docs/PHASE40_GOLDEN_MASTER_QA_REPORT.md',
  './docs_PHASE39E_FULL_APP_SMOKE_QA_BYPASS.md',
  './tests_phase39e_full_app_smoke.html',
  './js/qa-smoke-runner.js',
  './phase39e_static_qa.py',
  './phase39e_static_qa_result.json',
  './docs_PHASE39D_BUTTON_TOUCH_TARGET_NORMALISIERUNG.md',
  './tests_phase39d_touch_targets.html',
  './phase39d_static_qa.py',
  './phase39d_static_qa_result.json',
  './docs_PHASE39C_ICON_SYSTEM_DASHBOARD_UNIFICATION.md',
  './docs_PHASE39C2_SVG_DASHBOARD_QA_REST_EMOJI_CLEANUP.md',
  './tests_phase39c2_svg_dashboard_qa.html',
  './phase39c2_static_qa.py',
  './phase39c2_static_qa_result.json',
  './phase39c_static_integrity_check.py',
  './phase39c_static_integrity_result.json',
  './docs_PHASE39B_ADMIN_SCROLL_PERFORMANCE_FIX.md',
  './tests_phase39b_admin_scroll_performance.html',
  './phase39b_static_qa.py',
  './phase39b_static_qa_result.json',
  './phase39b_scroll_perf_audit_result.json',
  './docs_PHASE39A_FULL_UX_AUDIT.md',
  './tests_phase39a_full_ux_audit.html',
  './phase39a_full_ux_audit.py',
  './phase39a_full_ux_audit_result.json',
  './phase39a_static_qa_result.json',
  './qa_phase39a_screenshots/desktop-home.png',
  './qa_phase39a_screenshots/desktop-language-dashboard.png',
  './qa_phase39a_screenshots/desktop-exam-dashboard.png',
  './qa_phase39a_screenshots/desktop-admin.png',
  './qa_phase39a_screenshots/ipad-home.png',
  './qa_phase39a_screenshots/ipad-language-dashboard.png',
  './qa_phase39a_screenshots/ipad-exam-dashboard.png',
  './qa_phase39a_screenshots/ipad-admin-fresh.png',
  './qa_phase39a_screenshots/iphone-home-demo.png',
  './tests_phase38e2_weakness_profile.html',
  './tests_phase38e3_training_mode.html',
  './tests_phase38e5_mini_training_progress.html',
  './phase38e5_static_qa_result.json',
  './docs_PHASE38E2_WEAKNESS_PROFILE.md',
  './docs_PHASE38E3_TRAINING_MODE.md',
  './docs_PHASE38E5_MINI_TRAINING_PROGRESS.md',
  './tests_phase38e1_exam_dashboard.html',
  './docs_PHASE38E1_EXAM_DASHBOARD.md',
  './phase38d8_visual_deploy_qa_result.json',
  './phase38d8_visual_deploy_qa.py',
  './tests_phase38d8_visual_deploy_qa.html',
  './docs_PHASE38D8_VISUAL_DEPLOY_QA.md',
  './phase38d7_node_qa_result.json',
  './phase38d7_node_qa_runner.js',
  './tests_phase38d7_b2_gesamt_qa.html',
  './docs_PHASE38D7_B2_GESAMT_QA.md',
  './tests_phase38b_complete_speaking_exam_integration.html',
  './docs_PHASE38B_COMPLETE_GROQ_SPEAKING_EXAM.md',
  './docs_PHASE38C1_EXAM_ARCHITECTURE_HARD_RUBRIC.md',
  './tests_phase38c1_exam_engine_hard_rubric.html',
  './docs_PHASE38C2_EXAM_SHELL.md',
  './docs_PHASE38C3_B1_PILOT_HARD_EXAM.md',
  './tests_phase38c2_exam_shell.html',
  './tests_phase38c3_b1_pilot_hard_exam.html',
  './docs_PHASE38C4_B1_FINAL_REPORT.md',
  './tests_phase38c4_b1_final_report.html',
  './docs_PHASE38C5_B1_AUFGABENPOOL.md',
  './tests_phase38c5_b1_aufgabenpool.html',
  './docs_PHASE38C6_B1_AUFGABENPOOL_HAERTEFAELLE.md',
  './tests_phase38c6_b1_haertefaelle.html',
  './docs_PHASE38C7_B1_PRUEFUNGSGEFUEHL_TIMER.md',
  './tests_phase38c7_b1_pruefungsgefuehl_timer.html',
  './docs_PHASE38C8_B1_HOERPRUEFUNG_REALISTISCH.md',
  './tests_phase38c8_b1_hoerpruefung_realistisch.html',
  './docs_PHASE38C9_B1_SCHREIBPRUEFUNG_HART.md',
  './tests_phase38c9_b1_schreibpruefung_hart.html',
  './docs_PHASE38C10_B1_SPRECHPRUEFUNG_HART.md',
  './tests_phase38c10_b1_sprechpruefung_hart.html',
  './docs_PHASE38C11_B1_VOLLPRUEFUNG_QA.md',
  './tests_phase38c11_b1_vollpruefung_qa.html',
  './docs_PHASE38C12A_HARDMODE_UX_FIX.md',
  './tests_phase38c12a_hardmode_ux_fix.html',
  './admin-portal.html',
  './assets/logic/gemeinsamkeiten_1.png',
  './assets/logic/gemeinsamkeiten_2.png',
  './assets/logic/gemeinsamkeiten_3.png',
  './assets/logic/gemeinsamkeiten_4.png',
  './assets/logic/gemeinsamkeiten_5.png',
  './assets/logic/zugehoerigkeiten1_1.png',
  './assets/logic/zugehoerigkeiten1_2.png',
  './assets/logic/zugehoerigkeiten1_3.png',
  './assets/logic/zugehoerigkeiten2_2.png',
  './assets/logic/zugehoerigkeiten2_3.png',
  './assets/logic/zugehoerigkeiten2_4.png',
  './assets/logic/zugehoerigkeiten2_5.png',
  './assets/matrix/matrix_task_1.png',
  './assets/matrix/matrix_task_2.png',
  './assets/matrix/matrix_task_3.png',
  './assets/matrix/matrix_task_4.png',
  './assets/matrix/matrix_task_5.png',
  './assets/matrix/matrix_task_6.png',
  './assets/matrix/matrix_task_7.png',
  './assets/matrix/matrix_task_8.png',
  './assets/ui/brain-logo.svg',
  './assets/ui/hero-target-ios.svg',
  './assets/ui/hero-target.svg',
  './assets/ui/icon-analysis.svg',
  './assets/ui/icon-coach.svg',
  './assets/ui/icon-dashboard.svg',
  './assets/ui/icon-individual.svg',
  './assets/ui/icon-it.svg',
  './assets/ui/icon-kaufm-ios.svg',
  './assets/ui/icon-kaufm.svg',
  './assets/ui/icon-knowledge.svg',
  './assets/ui/icon-learn.svg',
  './assets/ui/icon-more.svg',
  './assets/ui/icon-practice.svg',
  './assets/ui/icon-progress.svg',
  './assets/ui/icon-settings.svg',
  './assets/ui/icon-social.svg',
  './assets/ui/icon-user.svg',
  './css/admin-portal.css',
  './css/app.css',
  './css/learning-coach.css',
  './css/language-course.css',
  './css/python-quest.css',
  './css/ui-foundation.css',
  './css/ui-nav-foundation.css',
  './css/cinematic.css',
  './css/egt-gate.css',
  './css/egt-simulation.css',
  './css/egt-practice.css',
  './css/ui-spacing-polish.css',
  './css/ui-density-grid-polish.css',
  './css/ui-ios-coach-polish.css',
  './css/phase25-release-qa-fixes.css',
  './css/phase26-product-structure.css',
  './modules/flowlogic/src/flowlogic.css',
  './css/ctc-flowlogic-integration.css',
  './css/ctc-lohr-real-exam.css',
  './data/admin-sync-config.js',
  './data/cloud-config.js',
  './data/language-ai-config.js',
  './data/coach-knowledge-base.js',
  './data/coach-knowledge-extended.js',
  './data/learning-math-tasks-extended.js',
  './data/learning-math-tasks.js',
  './data/python-quest-db.js',
  './data/question-bank-it-extra.js',
  './data/question-bank-kaufm.js',
  './data/question-bank-mathe.js',
  './data/question-bank-sozial.js',
  './data/question-bank.js',
  './data/question-schema.example.json',
  './docs/G25_DOZENTENFOKUS_REPORT.md',
  './docs/G25_DOZENTENFOKUS_QA.json',
  './docs/G25_1_HILFEBEDARF_DROPDOWN_REPORT.md',
  './docs/G25_1_HILFEBEDARF_DROPDOWN_QA.json',
  './docs/G26_1_SYSTEMINFO_TASKCOUNT_FIX_REPORT.md',
  './docs/G26_1_SYSTEMINFO_TASKCOUNT_FIX_QA.json',
  './docs/G26_SYSTEMINFO_DIAGNOSE_REPORT.md',
  './docs/G26_SYSTEMINFO_DIAGNOSE_QA.json',
  './icons/app-logo.svg',
  './icons/icon-180.png',
  './icons/icon-192.png',
  './icons/icon-512.png',
  './icons/maskable-512.png',
  './index.html',
  './js/admin-participant-engine.js',
  './js/app.js',
  './js/coach-dna-engine.js',
  './js/components/component-registry.js',
  './js/core/app-config.js',
  './js/core/architecture-guard.js',
  './js/core/event-bus.js',
  './js/core/module-host.js',
  './js/core/branch-question-pools.js',
  './js/core/question-bank-router.js',
  './js/core/generator-registry.js',
  './js/core/quiz-orchestrator.js',
  './js/core/question-factory.js',
  './js/core/ctc-lohr-exam-structure-engine.js',
  './js/core/ctc-simulation-stability-engine.js',
  './js/core/ctc-admin-report-engine.js',
  './js/core/quiz-build-pipeline-engine.js',
  './js/core/result-review-engine.js',
  './js/core/result-persistence-engine.js',
  './js/core/result-flow-engine.js',
  './js/core/question-flow-engine.js',
  './js/core/highscore-dashboard-engine.js',
  './js/core/cloud-highscore-engine.js',
  './js/core/highscore-duel-ui-engine.js',
  './js/core/duell-runtime-engine.js',
  './js/core/highscore-duel-sheet-router-engine.js',
  './js/core/admin-portal-domain-engine.js',
  './js/core/profile-auth-domain-engine.js',
  './js/core/coach-analysis-domain-engine.js',
  './js/core/product-structure-engine.js',
  './js/core/release-qa-engine.js',
  './js/modules/egt-home-module.js',
  './js/modules/egt-simulation-entry-module.js',
  './js/modules/egt-sim-it.js',
  './js/modules/egt-sim-kaufm.js',
  './js/modules/egt-sim-sozial.js',
  './js/modules/egt-practice-entry-module.js',
  './js/modules/egt-practice.js',
  './js/modules/egt-admin-entry-module.js',
  './js/modules/egt-profile-entry-module.js',
  './js/modules/egt-coach-entry-module.js',
  './js/modules/egt-analysis-data-adapter.js',
  './js/modules/egt-analysis-entry-module.js',
  './js/modules/egt-highscore-entry-module.js',
  './js/modules/egt-duel-entry-module.js',
  './js/core/feature-gates.js',
  './js/core/github-sync.js',
  './js/core/production-diagnostics.js',
  './js/core/router.js',
  './js/core/schema.js',
  './js/core/state-manager.js',
  './js/essay-mode.js',
  './js/feedback-sheet.js',
  './js/learning-coach-engine.js',
  './js/learning-coach-ui.js',
  './js/modules/language-ai-client.js',
  './js/modules/language-speaking-ai-client.js',
  './data/language-exam-blueprints.js',
  './data/language-level-difficulty-rules.js',
  './data/language-b1-exam-pilot.js',
  './data/language-b2-exam-pilot.js',
  './js/modules/language-exam-engine.js',
  './js/modules/language-exam-shell.js',
  './js/learning-task-generator.js',
  './js/module-registry.js',
  './js/modules/module-loader.js',
  './js/modules/auth-profile-shell.js',
  './js/modules/highscore-engine.js',
  './modules/flowlogic/src/flowlogic.selftest.js',
  './modules/flowlogic/src/flowlogic.schema.js',
  './modules/flowlogic/src/flowlogic.scenarios.js',
  './modules/flowlogic/src/flowlogic.mutations.js',
  './modules/flowlogic/src/flowlogic.validator.js',
  './modules/flowlogic/src/flowlogic.renderer.js',
  './modules/flowlogic/src/flowlogic.input.js',
  './modules/flowlogic/src/flowlogic.scorer.js',
  './modules/flowlogic/src/flowlogic.generator.js',
  './modules/flowlogic/src/flowlogic.module.js',
  './js/modules/ctc-flowlogic-adapter.js',
  './js/modules/egt-simulation-engine.js',
  './js/python-quest-module.js',
  './js/question-bank-quality-engine.js',
  './js/ui-home-renderer.js',
  './js/ui-router.js',
  './js/modules/cinematic-intro.js',
  './js/modules/egt-auth-engine.js',
  './js/modules/egt-ticket-system.js',
  './js/modules/egt-user-notices.js',
  './js/modules/egt-gate-screen.js',
  './js/modules/egt-gate-enforce.js',
  './manifest.json',
  './module-manifest.json',
  './modules/README.md',
  './modules/_template.js',
  './docs/G23_ADMIN_PORTAL_SHELL_REPORT.md',
  './docs/G23_ADMIN_PORTAL_SHELL_QA.json',
  './docs/G23_9_DEMO_TEILNEHMER_REPORT.md',
  './docs/G23_9_DEMO_TEILNEHMER_QA.json',
  './docs/G23_10_ROLLEN_DASHBOARD_REPORT.md',
  './docs/G23_11_DASHBOARD_TEILNEHMER_DROPDOWN_REPORT.md',
  './docs/G23_11_DASHBOARD_TEILNEHMER_DROPDOWN_QA.json',
  './docs/G27_1_QBANK_TAB_FIX_REPORT.md',
  './docs/G27_QBANK_QUALITY_QA.json',
  './docs/G28_EXPORT_BERICHTE_REPORT.md',
  './docs/G28_EXPORT_BERICHTE_QA.json',
  './docs/G29_PORTAL_POLISH_REPORT.md',
  './docs/G29_PORTAL_POLISH_QA.json',
  './docs/G30_TRAINING_COCKPIT_REPORT.md',
  './docs/G30_TRAINING_COCKPIT_QA.json',
  './docs/G30_2_TRAINING_COCKPIT_LAYOUT_FIX_REPORT.md',
  './docs/G30_2_TRAINING_COCKPIT_LAYOUT_FIX_QA.json',
  './docs/G30_3_QUESTION_OVERVIEW_POLISH_REPORT.md',
  './docs/G30_3_QUESTION_OVERVIEW_POLISH_QA.json',
  './docs/G30_4_ANSWER_LAYOUT_SPEED_FIX_REPORT.md',
  './docs/G30_4_ANSWER_LAYOUT_SPEED_FIX_QA.json',
  './docs/G32_4_FIREBASE_USERDATABASE_FOUNDATION_REPORT.md',
  './docs/G32_4_FIREBASE_FIRESTORE_RULES_EXAMPLE.txt',
  './docs/G33_0_AUTH_PROFILE_SHELL_REPORT.md',
  './docs/G33_0_AUTH_PROFILE_SHELL_QA.json',
  './docs/G33_5_DEMO_GATES_HIGHSCORE_PROFILE_REPORT.md',
  './docs/G33_5_DEMO_GATES_HIGHSCORE_PROFILE_QA.json',
  './docs/G34_1_DUEL_SYNC_FOUNDATION_REPORT.md',
  './docs/G34_1_DUEL_SYNC_FOUNDATION_QA.json',
  './docs/G34_1_FIRESTORE_RULES_ROLE_DRAFT.txt',
  './update-check.json',
  './service-worker.js',


  './docs/G33_1_FIREBASE_ACCESS_CODE_SHELL_REPORT.md',
  './docs/G33_1_FIREBASE_ACCESS_CODE_SHELL_QA.json',
  './docs/G33_2_ACCESS_CODE_GENERATOR_REPORT.md',
  './docs/G33_2_ACCESS_CODE_GENERATOR_QA.json',
  './docs/G33_2_FIREBASE_CONFIGURED_REPORT.md',
  './docs/G33_4_AVATAR_UPLOAD_HOTFIX_REPORT.md',
  './docs/G33_4_AVATAR_UPLOAD_HOTFIX_QA.json',
  './docs/G33_7_DEEP_SHEET_SIMULATION_FIX_QA.json',
  './docs/G33_7_DEEP_SHEET_SIMULATION_FIX_REPORT.md',
  './docs/G33_3_PROFILE_AVATAR_NICKNAME_REPORT.md',
  './docs/G33_3_PROFILE_AVATAR_NICKNAME_QA.json',
  './docs/G33_6_DEMO_SIMULATION_HOTFIX_REPORT.md',
  './docs/G33_6_DEMO_SIMULATION_HOTFIX_QA.json',
  './docs/G33_8_DEMO_DEEPSHEET_DIRECT_SIMULATION_REPORT.md',
  './docs/G33_8_DEMO_DEEPSHEET_DIRECT_SIMULATION_QA.json',
  './docs/G33_9_DEMO_SIMULATION_VIEWPORT_FIX_REPORT.md',
  './docs/G33_9_DEMO_SIMULATION_VIEWPORT_FIX_QA.json',
  './docs/G34_0_COACH_PROFILE_PERSONALIZATION_REPORT.md',
  './docs/G34_0_COACH_PROFILE_PERSONALIZATION_QA.json',
  './docs/G34_2_FINAL_QA_REPORT.md',
  './docs/G34_2_FINAL_QA.json',
  './docs/G35_0_USER_CENTER_STEP1_REPORT.md',
  './docs/G35_0_USER_CENTER_STEP1_QA.json',
  './docs/G37_4_CACHE_STRATEGY_FIX_REPORT.md',
  './docs/G37_5_BACKEND_CLEANUP_REPORT.md',
  './docs/G37_6_INTRO_VIDEO_REPORT.md',
  './docs/G38_0_STABLE_REPORT.md',
  './docs/G44_0_PHASE6_BRANCH_QUESTION_POOLS_REPORT.md',
  './docs/G44_0_PHASE6_BRANCH_QUESTION_POOLS_QA.json',
  './tests_phase38c12a2_deep_contrast_listening_qa.html',
  './docs_PHASE38C12A2_DEEP_CONTRAST_LISTENING_QA.md',
  './docs_PHASE38C12B_HOERPRUEFUNG_FINAL.md',
  './tests_phase38c12b_hoerpruefung_final.html',
  './docs_PHASE38C13_GRAMMATIK_SPRACHBAUSTEINE.md',
  './tests_phase38c13_grammar_sprachbausteine.html',
  './docs_PHASE38C14_B1_HARDMODE_GESAMT_QA.md',
  './tests_phase38c14_b1_hardmode_gesamt_qa.html',
  './docs_PHASE38D4_B2_GRAMMATIK_HART.md',
  './tests_phase38d5_b2_schreiben_hart.html',
  './docs_PHASE38D5_B2_SCHREIBEN_HART.md',
  './docs_PHASE38D6_B2_SPRECHEN_HART.md',
  './tests_phase38d6_b2_sprechen_hart.html',
  './tests_phase38d4_b2_grammatik_hart.html',
];

self.addEventListener('install', function (event) {
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE_NAME).then(function (cache) {
      return cache.addAll(ASSETS).catch(function (e) {
        console.warn('Cache konnte nicht vollständig vorbereitet werden:', e);
      });
    })
  );
});

self.addEventListener('activate', function (event) {
  event.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(
        keys.filter(function (k) { return k !== CACHE_NAME; })
            .map(function (k) { return caches.delete(k); })
      );
    }).then(function () {
      return self.clients.claim();
    })
  );
});

self.addEventListener('fetch', function (event) {
  if (event.request.method !== 'GET') return;
  var url = new URL(event.request.url);
  if (url.origin !== location.origin) return;

  if (url.pathname.includes('update-check')) {
    event.respondWith(fetch(event.request, { cache: 'no-store' }).catch(function () { return caches.match(event.request); }));
    return;
  }

  // Layout-/Logik-Dateien (HTML-Navigation, CSS, App-JS unter /js/) network-first:
  // Online gewinnt immer die frischeste Datei -> Layout-Fixes erscheinen ohne Cache-Löschen.
  // Cache dient nur als Offline-Fallback.
  var path = url.pathname;
  var isNavigation = event.request.mode === 'navigate';
  var isStylesheet = /\.css(?:$|\?)/i.test(path);
  var isAppScript = path.indexOf('/js/') !== -1 && /\.js(?:$|\?)/i.test(path);

  if (isNavigation || isStylesheet || isAppScript) {
    event.respondWith(
      fetch(event.request).then(function (response) {
        if (response && response.status === 200) {
          var clone = response.clone();
          caches.open(CACHE_NAME).then(function (cache) { cache.put(event.request, clone); });
        }
        return response;
      }).catch(function () {
        return caches.match(event.request).then(function (cached) {
          return cached || (isNavigation ? caches.match('./index.html') : undefined);
        });
      })
    );
    return;
  }

  // Statische Assets (Bilder, SVG, Daten, Fragenbänke): cache-first für Tempo/Offline,
  // im Hintergrund einmalig nachladen, falls noch nicht im Cache.
  event.respondWith(
    caches.match(event.request).then(function (cached) {
      if (cached) return cached;
      return fetch(event.request).then(function (response) {
        if (!response || response.status !== 200) return response;
        var clone = response.clone();
        caches.open(CACHE_NAME).then(function (cache) { cache.put(event.request, clone); });
        return response;
      });
    })
  );
});
