global.window = global;
global.CTCFlowLogicAdapter = { createQuestion: function(){ return { type:'ctcFlowLogic', cat:'CTC-Logik: Wenn-Dann-Ablauf', group:'Logik', block:'6. CTC-Logik: Wenn-Dann-Ablauf', q:'CTC-Logik: Wenn-Dann-Ablauf', a:['Ablaufplan'], correct:0, time:780, specialTimeSeconds:780, helpAllowed:false, coachDuring:false, branch:'it', simType:'ctc', poolKey:'it-ctc' }; } };
require('../js/core/ctc-lohr-exam-structure-engine.js');
const E = global.EGTCTCLohrExamStructureEngine;
const profile={branch:'it',simType:'ctc',mode:'ctcLohr',poolKey:'it-ctc'};
const qs = E.createExam({questionProfile:profile,mode:'ctcLohr'});
const counts = qs.reduce((a,q)=>{ a[q.type]=(a[q.type]||0)+1; return a; },{});
const blocks = qs.reduce((a,q)=>{ a[q.block]=(a[q.block]||0)+1; return a; },{});
const failures=[];
if(qs.length!==62) failures.push('expected 62 questions got '+qs.length);
if(E.totalSeconds()!==1978) failures.push('expected 1978 seconds got '+E.totalSeconds());
if(blocks['1. Allgemeinwissen']!==40) failures.push('general count');
if(blocks['2. Mathematik Sprint']!==9) failures.push('math count');
if(blocks['3. CTC-Regelrechnung']!==6) failures.push('rule count');
if(blocks['4. Buchstaben-Konzentration']!==4) failures.push('letter count');
if(blocks['5. Tabellen ablesen']!==2) failures.push('coord count');
if(blocks['6. CTC-Logik: Wenn-Dann-Ablauf']!==1) failures.push('flow count');
const rule = qs.find(q=>q.type==='ctcRuleArithmeticInput');
if(!rule || !rule.formula || rule.formula.indexOf('/')<0 || /\n|<hr|frac|fraction/i.test(rule.formula)) failures.push('rule formula not inline slash');
if(!rule || !Array.isArray(rule.a) || rule.a.length!==1) failures.push('rule must be input-style single answer');
if(E.createQuestion({index:0,questionProfile:{branch:'it',simType:'bps',mode:'bps',poolKey:'it-bps'}})!==null) failures.push('scope leak bps');
if(E.createQuestion({index:0,questionProfile:{branch:'sozial',simType:'ctc',mode:'ctcLohr',poolKey:'sozial-bps'}})!==null) failures.push('scope leak sozial');
const result = { ok: failures.length===0, failures, counts, blocks, diagnostics:E.diagnostics(), sampleRule:rule && rule.formula };
console.log(JSON.stringify(result,null,2));
if(failures.length) process.exit(1);
